### ISSUE TITLE
Undefined method 'prepend'

### ISSUE THREAD

**Issue by marcguilera** [ankane/mailkick#16]
I'm experiencing this error. The only thing I did add the gem to the bundle, install and when I run rake db:migrate --trace (or other tasks to test) I get:

`rake aborted!
NoMethodError: undefined method `prepend' for ActionMailer::Base:Class
/var/lib/gems/1.9.1/gems/actionmailer-4.2.5.1/lib/action_mailer/base.rb:569:in `method_missing'
/var/lib/gems/1.9.1/gems/mailkick-0.1.4/lib/mailkick.rb:90:in `<top (required)>'
/home/marc/Documents/Programming/Code/ferlist/ferlistapi/config/application.rb:7:in `<top (required)>'
/home/marc/Documents/Programming/Code/ferlist/ferlistapi/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
marc@ubuntu-marc:~/Documents/Programming/Code/ferlist/ferlistapi$ rake db:migrate --trace
rake aborted!
NoMethodError: undefined method `prepend' for ActionMailer::Base:Class
/var/lib/gems/1.9.1/gems/actionmailer-4.2.5.1/lib/action_mailer/base.rb:569:in `method_missing'
/var/lib/gems/1.9.1/gems/mailkick-0.1.4/lib/mailkick.rb:90:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `block in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `require'
/usr/lib/ruby/vendor_ruby/bundler.rb:132:in `require'
/home/marc/Documents/Programming/Code/ferlist/ferlistapi/config/application.rb:7:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/marc/Documents/Programming/Code/ferlist/ferlistapi/Rakefile:4:in `<top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
marc@ubuntu-marc:~/Documents/Programming/Code/ferlist/ferlistapi$ rake db:migrate --trace
rake aborted!
NoMethodError: undefined method `prepend' for ActionMailer::Base:Class
/var/lib/gems/1.9.1/gems/actionmailer-4.2.5.1/lib/action_mailer/base.rb:569:in `method_missing'
/var/lib/gems/1.9.1/gems/mailkick-0.1.4/lib/mailkick.rb:90:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `block in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `require'
/usr/lib/ruby/vendor_ruby/bundler.rb:132:in `require'
/home/marc/Documents/Programming/Code/ferlist/ferlistapi/config/application.rb:7:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/marc/Documents/Programming/Code/ferlist/ferlistapi/Rakefile:4:in `<top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
`
If I remove the gem and run the bundle again the error disappears. I'm using rails 4.2.5.1 and the gem rails-api. 

Running rails generate mailkick:install outputs:

`/var/lib/gems/1.9.1/gems/actionmailer-4.2.5.1/lib/action_mailer/base.rb:569:in `method_missing': undefined method `prepend' for ActionMailer::Base:Class (NoMethodError)
	from /var/lib/gems/1.9.1/gems/mailkick-0.1.4/lib/mailkick.rb:90:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block (2 levels) in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `block in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `require'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:132:in `require'
	from /home/marc/Documents/Programming/Code/ferlist/ferlistapi/config/application.rb:7:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /var/lib/gems/1.9.1/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /var/lib/gems/1.9.1/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /var/lib/gems/1.9.1/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /var/lib/gems/1.9.1/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/lib/gems/1.9.1/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'`

Which seems to be referring to the same prepend issue.

**Comment by rainerborene** [comment]
`prepend` is a new feature in Ruby 2. make sure to install the latest version.
