### ISSUE TITLE
Applying to non-mailkick objects

### ISSUE THREAD

**Issue by scottrCT** [ankane/mailkick#19]
Our app has a PortalUser model that is a mailkick_user. We also have a User model that is not a mailkick_user.

When an email is sent to a portaluser, mailkick correctly uses the defined user_method in PortalUser to find the PortalUser from the db. It populates the link and does what it is supposed to do.

When an email is sent to anything else (whether a User or a hardcoded email address), mailkick is still trying to attach itself, and queries the User model by email address. Our User model doesn't have email address since it is LDAP auth through Devise. This fails and causes the email not to be sent.

**Comment by ankane** [comment]
Hey @scottrCT, what does your `user_method` look like?

Also, I've updated master to report errors in production instead of throwing errors (and not sending emails, which is bad!!)

**Comment by scottrCT** [comment]
In the PortalUser model:
```
mailkick_user
Mailkick.user_method = proc {|email| PortalUser.find_by_email(email) }
```
We are going to try setting this in an initializer as the mailkick default and see if that fixes the problem.

**Comment by ankane** [comment]
Cleaning up stale issues
