### ISSUE TITLE
Unclear how to send email through mailkick

### ISSUE THREAD

**Issue by onemanstartup** [ankane/mailkick#2]
In repo I found method mail_with_mailkick, but in readme nothing said about that. Does it automatically called for every sent email or you need to do that manually? What if I have marketing emails and simple emails like welcome email after sign up?

**Comment by kyleschmolze** [comment]
To use Mailkick, you just use the `mailkick_unsubscribe_url` method in your email templates. You don't need to call any special `mail` method.

Mailkick's [mailer class](https://github.com/ankane/mailkick/blob/master/lib/mailkick/mailer.rb) will override your `mail` function with one which first processes each email, and then sends it using the original `mail` method. It processes using the [processor class](https://github.com/ankane/mailkick/blob/master/lib/mailkick/processor.rb), which simply takes the email address of the email's first recipient, looks for a relevant user (or whatever model you're using), and generates a secure unsubscribe link for that user/email combo.

**Comment by ankane** [comment]
Thanks for the assist @kyleschmolze 👍
