### ISSUE TITLE
Mounting Mailkick::Engine

### ISSUE THREAD

**Issue by fahim** [ankane/mailkick#25]
```
Rails.application.routes.draw do
  mount Mailkick::Engine => "/mailkick"
end
```

is happening from within the gem's config/routes.rb file. Seems like an anti-pattern considering your other projects (Blazer, Ahoy). Also, this doesn't work for me. Had to vendor the gem and move it to my route.rb

**Comment by ankane** [comment]
Ahoy [mounts automatically](https://github.com/ankane/ahoy/blob/76ce69ccd7f8beadf42a12b87dabf0f01cd4a7c4/config/routes.rb#L2), but there's a `mount` option to disable it. Happy to accept a PR to make it an option.

**Comment by trostli** [comment]
I was having an issue with routes as well. Turns out I had the following in my routes.rb file that was causing the issue:
```
  get "/*route"  =>  "application#render_404"
```

**Comment by ankane** [comment]
I added a `mount` option for this.

**Comment by kaimantsch** [comment]
Question: this may be obvious, but how & where is this config var "mount: false" set? 

It might also be helpful to include this in the documentation. (It is necessary to force a particular route set order when using Comfy Mexican Sofa CMS gem.)
