### ISSUE TITLE
Subscription not found

### ISSUE THREAD

**Issue by saten** [ankane/mailkick#3]
When I click the unsubscribe link within a email, the web page says 'Subscription not found'. User is correctly unsubscribed, though

**Comment by wqsaali** [comment]
@saten  mailkick_unsubscribe_url is not working in my view, do u know how to use it?

**Comment by saten** [comment]
@wqsaali provided your view is an action mailer view, you just have to call the mailkick_unsubscribe_url helper in it. @ankane did you have any idea on this issue?

**Comment by wqsaali** [comment]
@saten when i placed mailkick_unsubscribed_url rails say its undefined may be due to i am using subscription controller as well and it is due to duplication. however i just remove gem and do the same manually
