### ISSUE TITLE
Sending email via bulk sendgrid (for example)

### ISSUE THREAD

**Issue by kelfink** [ankane/mailkick#31]
Looks like the mechanisms here don't work so well when we use the headers['X-SMTPAPI'] to send to hundreds of subscribers.   The mailkick_unsubscribe_url is based on the original :to value in the mail method.  I find myself adjusting the url helper to carry an additional token "-subscriberId-" in which send grid can resolve the values, so the url's back to the unsubscribe controller action have the real recipient's identity.

Is there a better / built-in way?

**Comment by ankane** [comment]
Hey @kelfink, Mailkick isn't designed for this. You'll want to use Sendgrid directly to manage unsubscribes.
