### ISSUE TITLE
uninitialized constant Gibbon::API (NameError)

### ISSUE THREAD

**Issue by austinarchibald** [ankane/mailkick#33]
Trying to use this gem with Gibbon, and I get this error every time I try to load up the rails s or c. Thanks in advance.

`/Users/austin/.rvm/gems/ruby-2.4.1@rails5.1.4/gems/mailkick-0.2.0/lib/mailkick/service/mailchimp.rb:7:in `initialize': uninitialized constant Gibbon::API (NameError)`

**Comment by ankane** [comment]
Hey @austinarchibald, thanks for reporting 👍  It now works with the latest version of Gibbon.
