### ISSUE TITLE
Secret should not be nil error on upgrading to 0.3.0

### ISSUE THREAD

**Issue by dosco** [ankane/mailkick#37]
`2018-04-21T05:20:34.713Z 1 TID-owuox7dqh WARN: ActionView::Template::Error: Secret should not be nil.
2018-04-21T05:20:34.713Z 1 TID-owuox7dqh WARN: /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/message_verifier.rb:107:in `initialize'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/messages/rotator.rb:7:in `initialize'
/usr/local/bundle/gems/mailkick-0.3.0/lib/mailkick.rb:91:in `new'
/usr/local/bundle/gems/mailkick-0.3.0/lib/mailkick.rb:91:in `message_verifier'
/usr/local/bundle/gems/mailkick-0.3.0/lib/mailkick.rb:96:in `generate_token'
/usr/local/bundle/gems/mailkick-0.3.0/app/helpers/mailkick/url_helper.rb:9:in `mailkick_unsubscribe_url'
/app/app/views/layouts/mailer.html.erb:24:in `_app_views_layouts_mailer_html_erb__2296802602023607961_46968723266240'`

**Comment by ankane** [comment]
Hey @dosco, thanks for reporting 👍 Fixed on master.

**Comment by marckohlbrugge** [comment]
FWIW, I still get this error message on `rails 5.2.0` with `mailkick 0.3.1`.

**Comment by zywx** [comment]
@marckohlbrugge Same problem, how did you resolve it? I’m confused too!

**Comment by marckohlbrugge** [comment]
> @marckohlbrugge Same problem, how did you resolved it? I’m confused too!

This was a year ago, but seems like I got it fixed by setting a `secret_key_base`.

**Comment by zywx** [comment]
Yes it was because of this secret key.
