### ISSUE TITLE
EmailOctopus support

### ISSUE THREAD

**Issue by HLFH** [ankane/mailkick#39]
Hi,

Mailchimp and Mailjet do no support the blockchain industry.
EmailOctopus [supports it](https://emailoctopus.com/for-cryptocurrency).

https://github.com/tubbo/email_octopus may be helpful for a potential PR. 

Also the other idea would be to connect mailkick to [postal-rails](https://github.com/atech/postal-rails) and [postal](https://github.com/atech/postal).

**Comment by ankane** [comment]
Hey @HLFH, unfortunately, it doesn't look like EmailOctopus is very popular, and I think postal will be hard to test if it needs to be hosted itself.

**Comment by HLFH** [comment]
Hey @ankane. And what do you think of mailerlite who also supports the blockchain industry? https://www.mailerlite.com/

**Comment by ankane** [comment]
It doesn't look super popular either: https://github.com/jpalumickas/mailerlite-ruby

If it's something you're interested in maintaining, you can always create a new gem that adds functionality for another service.
