### ISSUE TITLE
After unsubscribe/resubscribe event?

### ISSUE THREAD

**Issue by tommytcchan** [ankane/mailkick#41]
Is there a way to accomplish adding listeners and/or overriding the controller to perform something (ie. also unsubscribe/resub to mailchimp) after the controller processes the request? 

If there isn't -- what is the best way to go about doing this?

Thanks in advance!

**Comment by tommytcchan** [comment]
In subscriptions_controller:

```
    def unsubscribe
      Mailkick.opt_out(@options)
      redirect_to subscription_path(params[:id])
    end

    def subscribe
      Mailkick.opt_in(@options)
      redirect_to subscription_path(params[:id])
    end
```

I'm thinking of the same mechanism as devise -- ie. having a `after_subscription_path` and `after_unsubscription_path` that by default points to the above paths but can be overridden by a custom controller class. Here's where we can do some post processing (ie. sending pings to unsub to 3rd party newsletter services like Sendy)

@ankane thoughts? TIA

**Comment by tommytcchan** [comment]
I suppose I could add something in after_create in the model `Mailkick::OptOut` as well

**Comment by ankane** [comment]
Hey @tommytcchan, an `after_save` on `Mailkick::OptOut` would be my recommendation.
