### ISSUE TITLE
How can we specify domain for a unsubscribe URL?

### ISSUE THREAD

**Issue by Sulavr96** [ankane/mailkick#44]
Actually, the backend of my app is deployed to heroku. So when I send an email with the unsubscribe link, after clicking on the link, I am redirected to localhost:3000. So How can I redirect the user to fixed url or specify domain for the unsubscribe url?

**Comment by ankane** [comment]
Hey @Sulavr96, Mailkick uses your Action Mailer settings when generating the unsubscribe URL. Make sure `config/environments/production.rb` has the correct options.

```ruby
config.action_mailer.default_url_options = {host: "yourhost.com"}
```
