### ISSUE TITLE
Sendgrid Integration - sendgrid_toolkit

### ISSUE THREAD

**Issue by ACPK** [ankane/mailkick#50]
Is there an alternative to using sendgrid_toolkit? I'm unable to use sendgrid_toolkit as mentioned in Mailkick's readme.

https://github.com/freerobby/sendgrid_toolkit/issues/53

**Comment by ankane** [comment]
Added support for the official gem to master.

```ruby
gem 'sendgrid-ruby`
```

And set `ENV["SENDGRID_API_KEY"]`. Requires just the "Suppressions" permission.

Let me know how it goes.
