### ISSUE TITLE
Rails routes 

### ISSUE THREAD

**Issue by leoplct** [ankane/mailkick#56]
I've installed the gem and added the "unsubscribe" link. However, I cannot find the mailkick route in routes.rb and in fact it's not rendered. It renders my homepage.

2) How can I get the unsubscribe link for a specific user_id ? Like mailkick_unsubscribe_url(user_id: id) ?

> /mailkick?locale=en/subscriptions/BAhbCUkiHWNocmlzdGluYUBpdHNudXRmYWlyLmNvbQY6BkVUaRBJIglVc2VyBjsARjA=--fe51a96fa69c038b472c76328d726898859befba/unsubscribe?locale=en

**Comment by ankane** [comment]
Hey @leoplct, unfortunately, I'm not sure how to reproduce with the info provided. It sounds like something in your application is interfering with the route.

**Comment by ankane** [comment]
Cleaning up issues
