### ISSUE TITLE
Support unsubscription through emails

### ISSUE THREAD

**Issue by xdmx** [ankane/mailkick#58]
Hi Andrew, have you thought about supporting unsubscriptions through emails?

I was [reading](https://blog.mailtrap.io/list-unsubscribe-header/) about the `List-Unsubscribe` header, and it seems that it supports both urls (which would be already covered by Mailkick) and mailto, but it seems that urls are only supported by gmail, all other providers won't use them, so it'd be better supporting mailto unsubscriptions as well.

Given that Rails now has ActionMailbox that would abstract the processing of incoming emails I was thinking if Mailkick would start support them as well. It could generate an unsubscription address that would be signed & unique for each user (and list type), and then it'd process them by unsubscribing the user as usual when an email is received.

What do you think? That'd be super useful

**Comment by ankane** [comment]
Hey @xdmx, thanks for the suggestion. It's an interesting idea, but probably not needed for most applications, as email services have this functionality built-in and allow you to retrieve unsubscribes through their API.

**Comment by xdmx** [comment]
Not SES :disappointed: :cry: 

Also, wouldn't it be useful for other services as well given that email services' unsubscriptions would be global unsubscriptions instead of having them tied to a specific Mailkick list?

**Comment by ankane** [comment]
Some services like SendGrid allow you to specify which list an email is part of so they're only unsubscribed from that list. Anyways, I think it's probably better as a separate gem if it's something you decide to build.

**Comment by xdmx** [comment]
I see what I can do :thinking:
