### ISSUE TITLE
Gem mandrill-api is deprecated

### ISSUE THREAD

**Issue by wscourge** [ankane/mailkick#71]
The [`mandrill-api`](https://rubygems.org/gems/mandrill-api) is deprecated and supposedly replaced by [`MailchimpTransactional`](https://rubygems.org/gems/MailchimpTransactional).

<img width="780" alt="image" src="https://user-images.githubusercontent.com/16985871/235869434-1fdf19bc-4cb2-4a30-a502-bd2b1ecdfa51.png">

Is it a drop-in replacement? Please advise on how to proceed.

**Comment by ankane** [comment]
Hi @wscourge, thanks for reporting. Feel free to submit a PR for a `MailchimpTransactional` service (will likely look similar to the [Mandrill one](https://github.com/ankane/mailkick/blob/master/lib/mailkick/service/mandrill.rb)).

**Comment by wscourge** [comment]
This is not about a **new service**, it is a bug report regarding an **existing one**.

**Comment by ankane** [comment]
You can continue to use the `mandrill-api` gem for the existing service.
