### ISSUE TITLE
generate token method should reference base class to avoid STI child class mismatch

### ISSUE THREAD

**Issue by haroldus-** [ankane/mailkick#73]
I think that the `base_class` should be referenced when generating the token since this is what is saved in the `subscriber_type` column:
```ruby
module Mailkick
...
  def self.generate_token(subscriber, list)
    raise ArgumentError, "Missing subscriber" unless subscriber
    raise ArgumentError, "Missing list" unless list.present?

    message_verifier.generate([nil, subscriber.id, subscriber.class.base_class.name, list])
  end
...
end
```

otherwise the child class name is referenced and the subscriber, being of a child class type, can't unsubscribe.

**Comment by ankane** [comment]
Hi @haroldus-, thanks for reporting! Fixed in the commit above.
