### ISSUE TITLE
Support on POST on routes for new Google guidelines?

### ISSUE THREAD

**Issue by xdmx** [ankane/mailkick#76]
Google recently published new guidelines that will start to be enforced in February: https://support.google.com/mail/answer/81126

One of which is "Make it easy to unsubscribe":

> Always give your recipients an easy way to unsubscribe from your messages. Letting people opt out of your messages can improve open rates, click-through rates, and sending efficiency. One-click unsubscribe makes it easy for people to opt out. If you send more than 5,000 message per day, your [marketing and subscribed messages must support one-click unsubscribe](https://support.google.com/mail/answer/81126#requirements-5k).

> To set up one-click unsubscribe, include both of these headers in outgoing messages:

>    List-Unsubscribe-Post: List-Unsubscribe=One-Click
>    List-Unsubscribe: <https://solarmora.com/unsubscribe/example>

> When a recipient unsubscribes using one-click, you receive this POST request:

```
"POST /unsubscribe/example HTTP/1.1
Host: solarmora.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 26
List-Unsubscribe=One-Click"
```

At the moment Mailkick only supports GET requests on the routes.

From my understanding [it should also not redirect](https://datatracker.ietf.org/doc/html/rfc8058#section-3.1):
> The mail sender MUST NOT return an HTTPS redirect, since redirected
> POST actions have historically not worked reliably, and many browsers
> have turned redirected HTTP POSTs into GETs.

**Comment by ankane** [comment]
Hi @xdmx, thanks for sharing! I pushed support in the [unsubscribe-headers branch](https://github.com/ankane/mailkick/compare/unsubscribe-headers), but still need to test it end-to-end.

**Comment by ankane** [comment]
It looks like Gmail [doesn't always](https://support.google.com/mail/thread/49653586?hl=en&msgid=49801705) show the unsubscribe link, but let me know if works for you and I'll merge.

**Comment by ankane** [comment]
Was able to test on iOS and confirm it's working.

**Comment by xdmx** [comment]
Awesome, thank you! I'll give it a try

**Comment by xdmx** [comment]
I've checked the code and it seems all good. I've also tried it out and I can see the headers being set.

In my case I'm going to not enable the `headers` config (smart one!), but only rely on the new POST route, because I also set an email alternative (since not all email clients support the url version) through an actionmailbox and the following was surprisingly causing the header to be duplicated (instead of replaced):

```ruby
    @unsubscribe_url = mailkick_unsubscribe_url(@recipient, list)
    headers["List-Unsubscribe"] = "<#{unsubscribe_email}>, <#{@unsubscribe_url}>"
```
