### ISSUE TITLE
Rails.application.secrets is deprecated

### ISSUE THREAD

**Issue by neoskunk** [ankane/mailkick#77]
After upgrading to rails 7.1, this gem causes

```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2.
```

Any chance we can get a release addressing this?  The offending line appears to be [here](https://github.com/ankane/mailkick/blob/6825505b7fc5c45c3c920e44038a2e7d8487fd2d/lib/mailkick/engine.rb#L17)

**Comment by ankane** [comment]
Hi @neoskunk, if you switch your app to using credentials, you shouldn't see this warning (see the code two lines above).
